version: "2.19.1"
services:
  web:
    build: .
    command: python3 /django_projects/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_projects
    ports:
      - "8000:8000"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib.postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: